### ISSUE TITLE
Problem with # caused when processing executable comments.

### ISSUE THREAD

**Issue by c-wind** [zr-hebo/sqlutil#1]
Hello:

I have a problem using your annotation function:

/*!40101 ######SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT /;

Returns after a call to comment.

/! 40101

**Comment by zr-hebo** [comment]
Hello, you are an attentive user. This is a bug that we have fixed.

**Comment by c-wind** [comment]
Thank you so much for solving a big problem that bothers me.
